#!/bin/sh
# dwfweb, static website generator, fault2004 @ 2023, MIT <https://github.com/fault2004/dwfweb>
[ ! -f smu/smu ] && (cd smu && make); [ -d o ] && rm -rf o; mkdir o; cp -r m o
for pd in p/*; do
p="${pd##*/}"; pe="${p%%.*}"
pn="$(echo "$pe" | cut -c 1,1 | tr '[:lower:]' '[:upper:]')$(echo "$pe" | cut -c2-)"
{
    sed "s/TITLE/${pn}/g" header
    for pl in p/*; do
        P="${pl##*/}"; PE="${P%%.*}"
        PN="$(echo "$PE" | cut -c 1,1 | tr '[:lower:]' '[:upper:]')$(echo "$PE" | cut -c2-)"
        [ "$PE" != "index" ] && echo "<a id=menu_link href=${PE}.html>${PN}</a>"
    done
    echo "</div>"
    smu/smu p/"$p"
    sed "s/DATE/$(date)/g" footer
} > o/"$pe".html
done
